all:
	Rscript -e 'rmarkdown::render("Binomial-Distribution.Rmd")'


pdf:
	Rscript -e 'rmarkdown::render("Binomial-Distribution.Rmd", output_format="pdf_document")'


html: 
	Rscript -e 'rmarkdown::render("Binomial-Distribution.Rmd", output_format="html_document")'


clean:
	rm Binomial-Distribution.pdf Binomial-Distribution.html Binomial-Distribution.log