---
title: "Binomial Option Pricing: Basic Principles"
subtitle: "Financial 5350: Computational Finance"
author: Tyler J. Brough
institute: Department of Finance and Economics 
titlegraphic: ./images/vertical-logo-blue.png
fontsize: 10pt
output:
 beamer_presentation:
    template: ./template.tex
    keep_tex: false
    toc: true
make149: true
---


# Section 10.1: A One-Period Binomial Tree

## Introduction to Binomial Option Pricing

* The binomial option pricing model enables us to determine the price of an option, given the characteristics of the stock or other underlying asset

* The binomial option pricing model assumes that the price of the underlying asset follows a binomial distribution - that is, the asset price in each Period
  can move only up or down by a specified amount

* The binomial model is often referred to as the "Cox-Ross-Rubinstein pricing model"


## A One-Period Binomial Tree

* Example
    - Consider a European call option on the stock of XYZ, with a $\$40$ strike and 1 year to expiration
    - XYZ does not pay dividends (i.e. $\delta =0$), and its current price is $S_{0} = \$41$
    - The continuously compounded risk-free interest rate is $8\%$ (i.e. $r = 0.08$)
    - The following is the corresponding binomial tree:

\vspace{30mm}

\phantom{}


## Computing the Option Price

* Next, consider two portfolios:
    - _Portfolio A:_ buy one call option
    - _Portfolio B:_ buy $2/3$ shares of XYZ and borrow $\$18.462$ at the risk-free rate, $r$

\vspace{5mm}

* Portfolio Costs:
    - _Portfolio A:_ the call premium, __which is unknown and what we are solving for__
    - _Portfolio B:_ $2/3 \times \$41 - \$19.462 = \$8.871$



## Computing the Option Price Continued

* Payoffs:

\vspace{55mm}

## Computing the Option Price Continued

* Portfolios A and B have the same payoff. Therefore:
    - Portfolios A and B should have the same cost. Since Portfolio B costs $\$8.871$, the price of on option must also be $\$8.871$
    - There is a way to create the payoff to a call by buying shares and borrowing. Portfolio B is a _synthetic call_
    - One option has the risk of $2/3$ shares. The value $2/3$ is the $delta$ ($\Delta$) of the option: the number of shares that replicates the option payoff


## The Bimonial Solution

* How do we find a replicating portfolio consisting of $\Delta$ shares of stock and a dollar amount $B$ in lending, such that the portfolio imitates the option
  whether the stock or falls? 
    - Suppose that the stock has a continuous dividend yield of $\delta$, which is reinvested in the stock. Thus, if you buy one share at time $t$, at time $t+h$
      you will have $e^{\delta h}$ shares 
    - If the length of a period is $h$, the interest factor per period is $e^{rh}$
    - $uS$ denotes the stock price when the price goes up, and $dS$ denotes the stock price when the price goes down


## The Binomial Solution Continued

\vspace{45mm}

* The value of the replicating portfolio at time $h$, with stock price $S_{h}$, is

$$
\Delta S_{h} e^{\delta h} + e^{rh}B
$$

## The Binomial Solution Continued

* At the prices $S_{h} = uS$ and $S_{h} = dS$, a successful replicating portfolio will satisfy

$$
\begin{aligned}
(\Delta \times uS \times e^{\delta h}) + (B \times e^{rh}) &= C_{u} \\
(\Delta \times dS \times e^{\delta h}) + (B \times e^{rh}) &= C_{d}
\end{aligned}
$$


* Solving for $\Delta$ and $B$ gives

$$
\begin{aligned}
\Delta &= e^{-\delta h} \left(\frac{C_{u} - C_{d}}{S(u - d)} \right) \\
& \\
B &= e^{-rh} \left(\frac{uC_{d} - dC_{u}}{u - d} \right)
\end{aligned}
$$

\tiny \textbf{NB:} Please see notes on the full algebraic derivation.


## The Bimonial Solution Continued

* The cost of creating the option is the net cash flow required to buy the shares and bonds.
  Thus, the cost of the option is $\Delta S + B$

$$
\Delta S + B = e^{-rh}\left(C_{u} \frac{e^{(r - \delta) h} - d}{u-d} + C_{d} \frac{u - e^{(r - \delta) h}}{u-d} \right)
$$

\vspace{10mm}

* The no-arbitrage condition is

$$
d < e^{(r - \delta) h} < u
$$


## Arbitraging a Mispriced Option

If the observed option price differs from its theoretical price, arbitrage is possible:

\vspace{3mm}

- If an option is overpriced, we can sell the option. However, the risk is that the option will be in the 
  money at expiration, and we will be required to deliver the stock. To hedge this risk, we can buy
  a synthetic option at the same time we sell the actual option

\vspace{3mm} 

- If an option is underpriced, we buy the option. To hedge the risk associated with the possibility of
  the stock price falling at expiration, we sell a synthetic option at the same time


## Arbitraging a Mispriced Option Continued

\phantom{}


## Risk-Neutral Pricing

* We can interpret the terms $\frac{(e^{(r - \delta) h} - d)}{(u-d)}$ and 
  $\frac{(u - e^{(r - \delta) h})}{u-d}$ as probabilities

* Let 

$$
p^{\ast} = \frac{e^{(r - \delta) h} -d}{u - d}
$$

* Then equation (10.3) can then be written as 

$$
C_{0} = e^{-rh} [p^{\ast}C_{u} + (1 - p^{\ast})C_{d}]
$$

* We call $p^{\ast}$ the \textbf{risk-neutral probability} of an increase in the stock price


## Summary 

* In order to price an option, we need to know the following:
    - Stock price ($S$)
    - Strike price($K$)
    - The expiration date of the options ($T$)
    - Standard deviation of returns on the stock ($\sigma$)
    - Divided yield ($\delta$)
    - Risk-free rate ($r$)

* Using the risk-free rate and $\sigma$, we can approximate the future distribution of the stock by creating a binomial tree using equation (10.9)

* Once we have the binomial tree, it is possible to price the option using equation (10.3)


# Section 10.2: Constructing A Binomial Tree

## Continuously Compounded Returns



## Volatility



## The Standard Deviation of Continuously Compounded Returns Continued



## Constructing $u$ and $d$



## Constructing $u$ and $d$ Continued



## Estimating Historical Volatility



## Estimating Historical Volatility Continued



## One-Period Example with a Forward Tree



## One-Period Example with a Forward Tree Continued



# Section 10.3: Two Or More Binomial Periods

## A Two-Period European Call



## A Two-Period European Call Continued



## Pricing the Call Option



## Pricing the Call Option Continued



## Pricing the Call Option Continued



## Many Binomial Periods



## Many Bimonial Periods Continued



## Many Bimonial Periods Continued


# Section 10.4: Put Options

## Put Options



## Put Options Continued



# Section 10.5: American Options

## American Options


## American Options Continued



## American Options Continued



## American Options Continued


# Section 10.6: Options on Other Assets

## Options on Other Assets



## Options on a Stock Index



## Options on a Stock Index Continued


## Options on Futures Contracts



## Options on Futures Contracts Continued



## Options on Futures Contracts Continued



## Options on Futures Contracts Continued



## Options on Commodities



## Options on Bonds



## Summary



## 
