---
title: "Market-Making and Delta Hedging"
author: "Tyler J. Brough"
date: "October 28, 2018"
output: slidy_presentation
---

# Market-Making and Delta Hedging

## Introduction

- Without hedging, an active market-maker will have an arbitrary position generated by fulfilling customer orders

- An arbitrary portfolio has uncontrolled risk
	* An adverse price move has the potential to bankrupt the market-maker

- Market-makers thus attempt to hedge the risk of their positions


## Delta Hedging for a Two-Day Period

- Consider a customer who wishes to buy a $91$-day call option, the market-maker fills this order by selling a call option

- Take the following as given:
	* $S = \$40$
	* $K = \$40$
	* $\sigma = 0.30$
	* $r = 0.08$
	* $\delta = 0$
	* $T - t = 91/365$


## Delta-Hedging Example Continued

__Day 0.__ Consider the $40-$strike call option described above, written on $100$ shares of stock. The market-maker sells the option and receives $\$278.04$. Since
$\Delta = 0.5824$, the market-maker also buys $58.24$ shares. 

The net investment is

$$
(58.24 \times \$40) - \$278.04 = \$2051.56
$$

At an $8\%$ interest rate, the market-maker has an overnight finance charge of
$\$2051.56 \times (e^{0.08/365} - 1) = \$0.45$.

## Delta-Hedging on Day 1 - Marking-to-Market

__Day 1: Marking-to-Market__. Suppose the new stock price is $\$40.50$. The new
call option price with $1$ day less to expiration and at the new stock price is
$\$3.0621$ (via Black-Scholes-Merton). Overnight mark-to-market profit is a gain
of $\$0.50$, computed as follows:

\begin{table}[h]
\centering
\begin{tabular}{lr}
Gain on $58.24$ shares      & $58.24 \times (\$40.50 - \$40) = \$29.12$         \\
Gain on written call option & $\$278.04 - \$306.21 = -\$28.17$                  \\ 
Interest                    &  $-(e^{0.08/365} - 1) \times \$2051.56 = -\$0.45$ \\
\hline
\textbf{Overnight Profit}   & \textbf{$\$0.50$}                                 \\
\end{tabular}
\end{table}


## Delta-Hedging on Day 1 - Rebalancing the Hedge 

__Day 1: Rebalancing the Portfolio.__ The new delta is $0.6142$. Since delta has
increased, we must buy $61.42 - 58.24 = 3.18$ additional shares. This will require
an investment of $\$40.50 \times 3.18 = \$128.79$. Since the readjustment in the 
number of shares entails buying at the current market price, it does not affect
the mark-to-market profits for that day. 


## Delta-Hedging on Day 2

__Day 2: Marking-to-Market.__ The stock price now falls to $\$39.25$. The
market-maker makes money on the written option and loses money on the $61.42$
shares. Interest increases over the previous day because additional investment
was required for the extra shares. The net result from marking-to-market is a 
loss of $-\$3.87$:

\begin{table}[h]
\centering
\begin{tabular}{lr}
Gain on $61.42$ shares      & $61.42 \times (\$39.25 - \$40.50) = -\$76.78$    \\
Gain on written call option & $\$306.21 - \$232.82 = \$73.39$                  \\
Interest                    & $-(e^{0.08/365} - 1) \times \$2181.30 = -\$0.48$ \\
\hline
\textbf{Overnight Profit}   & \textbf{-$\$3.87$}                                \\
\end{tabular}
\end{table}



