---
title: "Binomial Option Pricing: Basic Principles"
subtitle: "Financial 5350: Computational Finance"
author: Tyler J. Brough
institute: Department of Finance and Economics 
titlegraphic: ./images/vertical-logo-blue.png
fontsize: 10pt
output:
 beamer_presentation:
    template: ./template.tex
    keep_tex: false
    toc: false
make149: true
---


## Introduction to Binomial Option Pricing

\underline{\phantom{}}


## A One-Period Binomial Tree

\underline{\phantom{}}


## Computing the Option Price

\underline{\phantom{}}


## Computing the Option Price Continued

\underline{\phantom{}}


## Computing the Option Price Continued

\underline{\phantom{}}


## The Bimonial Solution

\underline{\phantom{}}


## The Binomial Solution Continued



## The Binomial Solution Continued



## The Bimonial Solution Continued



## Arbitraging a Mispriced Option



## Risk-Neutral Pricing



## Summary 



## Continuously Compounded Returns



## Volatility



## The Standard Deviation of Continuously Compounded Returns Continued



## Constructing $u$ and $d$



## Constructing $u$ and $d$ Continued



## Estimating Historical Volatility



## Estimating Historical Volatility Continued



## One-Period Example with a Forward Tree



## One-Period Example with a Forward Tree Continued



## A Two-Period European Call



## A Two-Period European Call Continued



## Pricing the Call Option



## Pricing the Call Option Continued



## Pricing the Call Option Continued



## Many Binomial Periods



## Many Bimonial Periods Continued



## Many Bimonial Periods Continued



## Put Options



## Put Options Continued



## American Options


## American Options Continued



## American Options Continued



## American Options Continued



## Options on Other Assets



## Options on a Stock Index



## Options on a Stock Index Continued


## Options on Futures Contracts



## Options on Futures Contracts Continued



## Options on Futures Contracts Continued



## Options on Futures Contracts Continued



## Options on Commodities



## Options on Bonds



## Summary



## 
