---
title: "The Heston Model"
author: "Tyler J. Brough"
date: "November 17, 2016"
output:
  html_document: default
  pdf_document: default
---

## The Heston Model

The Heston (1993) model assumes the underlying stock price follows the diffusion process given by:

$$
dS_{t} = \mu S_{t} dt + \sqrt{v_{t}} S_{t} dz_{1,t}
$$
where $\mu$ is the drift parameter, and $z_{1,t}$ is a standard Wiener process. The volatility $\sqrt{v_{t}}$ itself follows a diffusion process:

$$
d\sqrt{v_{t}} = -\beta \sqrt{v_{t}} dt + \delta dz_{2,t}
$$

where $z_{2,t}$ is a Wiener process, and $\rho$ defines the correlation between $z_{1,t}$ and $z{2,t}$. 

Using Ito's lemma the variance process can be written as an Orstein-Uhlenbeck (mean-reverting) process:

$$
dv_{t} = \kappa [\theta - v_{t}] dt + \sigma \sqrt{v_{t}} d z_{2,t}
$$

where

- $\theta$ is the long-run mean of the variance

- $\kappa$ is a mean reversion parameter 

- $\sigma$ is the volatility of volatility

Given this set up the Heston (1993) gives the price of the call option as:

$$
Call(S,v,t) = S_{t} P_{1} - K P(t,T) P_{2}
$$
where

- $S_{t}$ is the spot price of the asset

- $K$ is the strike price of the option

- $P(t,T)$ is a discount factor from time $t$ to time $T$

If we assume a constant rate of interest $r$, we can write this as

$$
P(t,T) = \exp{-r \times (T - t)}
$$

$P_{1}$ and $P_{2}$ are the probabilities that the call option will expire in-the-money, conditional on the log stock price $x_{t} = ln[S_{t}]$, and on the volatility $v_{t}$, each at time $t$. 

The risk-neutral versions are given by:

$$
\begin{aligned}
dx_{t} &= \left[r -\frac{1}{2}v_{t} \right] dt + \sqrt{v_{t}} dz_{1,t}^{\ast} \\
dv_{t} &= \kappa \left[\theta - v_{t} \right] dt + \sigma \sqrt{v_{t}} dz_{2,t}^{\ast}
\end{aligned}
$$

In order to simulate from these equations we require a discretized form of the equations. It turns out that there are
not closed-form solutions for these particular two equations. It is also the case that the standard Euler discretization
technique is possible, but in the case of the variance equation will produce draws that are negative values of
volatilitiy. There are a number of ways to deal with this. The one that we select here is to work with the natural
logarithm of the variance. Using Ito's lemma again we can get the dynamics of $\ln{(v_{t})}$ as follows:

$$
d \ln{(v_{t})} = \frac{1}{v_{t}} ( \kappa (\theta - v_{t}) - \frac{1}{2} \sigma^{2}) dt + \sigma \frac{1}{\sqrt{v_{t}}} dz_{2,t}^{\ast}
$$

When the Euler discretization scheme is applied we arrive at the following discrete time solutions:

$$
\begin{aligned}
\ln{(S_{t + \Delta t})} &= \ln{(S_{t})} + \left(r - \frac{1}{2} v_{t}\right) \Delta t + \sqrt{v_{t}} \sqrt{\Delta t} \varepsilon_{S,t+1}\\
\ln{(v_{t + \Delta t})} &= \ln{(v_{t})} + \frac{1}{v_{t}} \left(\kappa (\theta - v_{t}) - \frac{1}{2} \sigma^{2}\right) \Delta t + \sigma \frac{1}{\sqrt{v_{t}}} \sqrt{\Delta t} \varepsilon_{v,t+1}
\end{aligned}
$$
Shocks to the volatility, $\varepsilon_{v,t+1}$ are correlated with the shocks to the stock price process, $\varepsilon_{S,t+1}$. This is denoted by $\rho = Corr(\varepsilon_{v,t+1}, \varepsilon_{S,t+1})$ and the relationship between shocks can be written:

$$
\varepsilon_{v,t+1} = \rho \varepsilon_{S,t+1} + \sqrt{1 - \rho^{2}} \varepsilon_{t+1}
$$

where the $\varepsilon_{t+1}$ are iid Standard Normal variables that each have zero correlation with $\varepsilon_{S,t+1}$. 

We now illustrate how to simulate from the processes in Python for the following parameter values (these are taken from the original paper by Heston (1993)):

- $S = 100$

- $K = 100$

- $r = 0.0$

- $\tau = 180/365 = 0.5$

- $v = 0.01$

- $\rho = 0.0$

- $\kappa = 2.0$

- $\theta = 0.01$

- $\sigma = 0.10$






















