all:
	pweave -f markdown stochastic-volatility.pmd
	pandoc stochastic-volatility.md -o stochastic-volatility.pdf


word:
	pweave -f markdown stochastic-volatility.pmd
	pandoc stochastic-volatility.md -o stochastic-volatility.docx




clean:
	rm stochastic-volatility.md stochastic-volatility.pdf
