all:
	Rscript -e 'rmarkdown::render("Binomial-Distribution.Rmd")'


pdf:
	Rscript -e 'rmarkdown::render("Binomial-Distribution.Rmd", output_format="beamer_presentation")'


clean:
	rm Binomial-Distribution.pdf 